### ISSUE TITLE
Error in Summary tab when using custom blockmodel

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#11]
When custom blockmodel is used for blockmodeling, the following error is printed in Summary tab:
"Error: error in evaluating the argument 'x' in selecting a method for function 'print': 'MARGIN' does not match dim(X)"

If it matters, I was using the sample datasets, binary blockmodeling and a blockmodel with 3 groups, complete blocks on the diagonal and null blocks elsewhere.

**Comment by FATelarico** [comment]
Fixed. My conclusion is that Shiny cannot print an array if its first dimension is degenerate.

**Tentative explanation**
When building a custom block-model that supports only one block-type per cluster, the app was returning an array called `BlockTypes` with dimensions `1,1,nrow,ncol`. So, in this case, it was returning an array such that `dim(BlockTypes)=c(1,1,3,3)` , where both the first and the second dimension are degenerate. 

When calling an object of S3-class `OptMorePart`, Shiny tries to retrieve some sort of information from the array BlockTypes using `apply()`. But this function 'dislikes' the fact that the first dimension of the array is degenerate, possibly because it assumes such dimension is redundant. 

I fixed the issue by ensuring that the first dimension of the array is not degenerate using this code (rows 1815-7):
```
            if(dim(BlockTypes)[1]==1){
              BlockTypes<-BlockTypes[1,1,,]
            }
```
